### ISSUE TITLE
Subpar Code - G:Line Function/Method Rewrite

### ISSUE THREAD

**Issue by techhelper1** [blindirc/POPM#9]
Take out the multiple G:Line function/methods and replace them with 1 command for P10 and TS6. Define the G:Line messages in the config file.
Define {ip} {host} {port} {dnsbl} {proxytype} and string replace them with the actual data.

**Comment by blindirc** [comment]
Added in https://github.com/blindirc/POPM/commit/b76225feaa796d0efbcd650d024c2096aa7489f2 and https://github.com/blindirc/POPM/commit/9755514cdca889d659037019aa09022505b716cd
